abstract Phylo = {
    flags startcat = DMessage;
    flags startcat = Message;
    cat
        Message;
        Input;
        Output;
        Format;
    fun
        f_phylotastic_ResolvedScientificNames_GNR_TNRS_POST: Input -> Output -> Output -> Message;
        f_convert_species_tree_format_NMSU_to_NewickTree: Input -> Output -> Message;
        f_names_extraction_document: Input -> Output -> Message;
        f_phylotastic_GetSpeciesOfTaxon_Genome_NCBI_GET: Input -> Output -> Output -> Message;
        f_phylotastic_ResolvedScientificNames_OT_TNRS_GET: Input -> Output -> Output -> Message;
        f_convert_df_sci_names_format_1_to_3: Input -> Output -> Message;
        f_phylotastic_GetAllSpeciesFromTaxon_Country_OT_GET: Input -> Input -> Output -> Output -> Message;
        f_convert_df_sci_names_format_3_to_5: Input -> Output -> Message;
        f_convert_df_taxons_format_3_to_5: Input -> Output -> Message;
        f_phylotastic_GetPhylogeneticTree_OT_GET: Input -> Output -> Output -> Message;
        f_convert_species_tree_format_PhyloTree_to_phylo4Tree: Input -> Output -> Message;
        f_convert_df_sci_names_format_6_to_OT: Input -> Output -> Message;
        f_convert_df_taxons_format_2_to_4: Input -> Output -> Message;
        f_convert_df_resolved_names_format_GNR_to_Phylomatic: Input -> Output -> Message;
        f_phylotastic_GetChronograms_ScaledSpeciesTree_DateLife_POST: Input -> Input -> Output -> Message;
        f_convert_gene_tree_format_PhyloTree_to_phylo4Tree: Input -> Output -> Message;
        f_taxon_to_species_operation: Input -> Output -> Output -> Message;
        f_convert_df_taxons_format_5_to_OT: Input -> Output -> Message;
        f_phylogeny_based_extraction: Input -> Output -> Message;
        f_convert_df_resolved_names_format_4_to_6: Input -> Output -> Message;
        f_convert_gene_tree_format_NewickTree_to_ALL_COMBO: Input -> Output -> Output -> Output -> Message;
        f_gene_tree_scaling: Input -> Output -> Message;
        f_tree_scaling_operation: Input -> Output -> Message;
        f_look_up_taxonomy: Output -> Message;
        f_phylotastic_GetPhylogeneticTree_Phylomatic_POST: Input -> Output -> Output -> Message;
        f_phylotastic_CompareTrees_Sym_Dendropy_POST: Input -> Input -> Output -> Output -> Message;
        f_convert_species_tree_format_1_to_2: Input -> Output -> Message;
        f_phylotastic_GetAllSpeciesFromTaxon_OT_GET: Input -> Output -> Output -> Message;
        f_phylotastic_GetSpeciesScientificNameFromCommonName_NCBI_GET: Input -> Output -> Output -> Message;
        f_phylotastic_GetReconciliationTree_GET: Input -> Input -> Output -> Message;
        f_convert_gene_tree_format_1_to_2: Input -> Output -> Message;
        f_convert_df_resolved_names_format_GNR_to_OT: Input -> Output -> Message;
        f_tree_transformation: Input -> Output -> Message;
        f_country_code_to_name: Input -> Output -> Message;
        f_phylotastic_GenerateGeneTree_From_Genes: Input -> Output -> Message;
        f_convert_df_taxons_format_1_to_3: Input -> Output -> Message;
        f_convert_gene_tree_format_NMSU_to_NewickTree: Input -> Output -> Message;
        f_convert_df_sci_names_format_5_to_OT: Input -> Output -> Message;
        f_phylotastic_GetPhylogeneticTree_PhyloT_GET: Input -> Output -> Output -> Message;
        f_convert_df_resolved_names_format_3_to_5: Input -> Output -> Message;
        f_names_operation: Output -> Message;
        f_phylotastic_FindScientificNamesFromWeb_CS_NMSU_GET: Input -> Output -> Message;
        f_scientific_name_to_taxonomy: Input -> Output -> Message;
        f_convert_df_resolved_names_format_1_to_3: Input -> Output -> Message;
        f_taxon_to_species_by_genome: Input -> Output -> Output -> Message;
        f_names_extraction_operation: Output -> Message;
        f_phylotastic_GetPhylogeneticTree_PhyloT_POST: Input -> Output -> Output -> Message;
        f_convert_df_resolved_names_format_5_to_PhyloT: Input -> Output -> Message;
        f_names_conversion_operation: Output -> Message;
        f_phylotastic_FindScientificNamesFromFreeText_GNRD_GET: Input -> Output -> Message;
        f_convert_df_taxons_format_GNR_to_OT: Input -> Output -> Message;
        f_names_resolution_operation: Input -> Output -> Output -> Message;
        f_common_name_to_scientific_name: Input -> Output -> Output -> Output -> Message;
        f_gene_based_extraction: Input -> Output -> Output -> Message;
        f_convert_df_resolved_names_format_5_to_Phylomatic: Input -> Output -> Message;
        f_phylotastic_ExtractSpeciesNames_From_Gene_Tree_GET: Input -> Output -> Message;
        f_convert_df_taxons_format_GNR_to_Phylomatic: Input -> Output -> Message;
        f_taxonomy_based_extraction: Input -> Output -> Message;
        f_look_up_scientific_name: Output -> Message;
        f_phylotastic_GeneTree_Scaling: Input -> Output -> Message;
        f_convert_df_resolved_names_format_5_to_OT: Input -> Output -> Message;
        f_convert_df_text_format_raw_to_plain: Input -> Output -> Message;
        f_phylotastic_FindScientificNamesFromWeb_GNRD_GET: Input -> Output -> Message;
        f_tree_reconciliation: Input -> Input -> Output -> Output -> Message;
        f_convert_species_tree_format_pHYLIPTree_to_PhyloTree: Input -> Output -> Message;
        f_phylotastic_GetMetadata_Chronogram_DateLife_POST: Input -> Output -> Message;
        f_phylotastic_ResolvedScientificNames_GNR_TNRS_GET: Input -> Output -> Output -> Message;
        f_tree_visualization: Input -> Output -> Message;
        f_convert_df_resolved_names_format_GNR_to_PhyloT: Input -> Output -> Message;
        f_convert_df_taxons_format_6_to_ALL_COMBO: Input -> Output -> Output -> Output -> Message;
        f_convert_species_tree_format_Phylo4Tree_to_PhyloTree: Input -> Output -> Message;
        f_convert_df_taxons_format_5_to_PhyloT: Input -> Output -> Message;
        f_convert_df_taxons_format_GNR_to_PhyloT: Input -> Output -> Message;
        f_convert_gene_tree_format_pHYLIPTree_to_PhyloTree: Input -> Output -> Message;
        f_species_tree_scaling: Input -> Input -> Output -> Message;
        f_convert_df_sci_names_format_5_to_GNR: Input -> Output -> Message;
        f_convert_species_tree_format_PhyloTree_to_NMSU: Input -> Output -> Message;
        f_convert_gene_tree_format_Phylo4Tree_to_PhyloTree: Input -> Output -> Message;
        f_convert_df_sci_names_format_4_to_6: Input -> Output -> Message;
        f_convert_species_tree_format_NewickTree_to_ALL_COMBO: Input -> Output -> Output -> Output -> Message;
        f_tree_extraction_operation: Output -> Message;
        f_tree_generation: Output -> Message;
        f_google_ConvertCountryCodeToName_GET: Input -> Output -> Message;
        f_convert_gene_tree_format_PhyloTree_to_NMSU: Input -> Output -> Message;
        f_convert_df_resolved_names_format_2_to_4: Input -> Output -> Message;
        f_phylotastic_CompareTrees_BL_Dendropy_POST: Input -> Input -> Output -> Output -> Message;
        f_convert_df_resolved_names_format_6_to_ALL_COMBO: Input -> Output -> Output -> Output -> Message;
        f_convert_species_tree_format_2_to_pHYLIPTree: Input -> Output -> Message;
        f_tree_metadata_chronogram: Input -> Output -> Message;
        f_taxon_to_species_by_country: Input -> Input -> Output -> Output -> Message;
        f_tree_retrieval_operation: Output -> Message;
        f_openTree_GetTaxonomyNameFromSciName_GET: Input -> Output -> Message;
        f_convert_df_taxons_format_4_to_6: Input -> Output -> Message;
        f_convert_gene_tree_format_2_to_pHYLIPTree: Input -> Output -> Message;
        f_convert_df_taxons_format_5_to_Phylomatic: Input -> Output -> Message;
        f_symmetric_comparison_operation: Input -> Input -> Output -> Output -> Message;
        f_phylotastic_GetPhylogeneticTree_OT_POST: Input -> Output -> Output -> Message;
        f_branch_length_comparison_operation: Input -> Input -> Output -> Output -> Message;
        f_names_extraction_web: Input -> Output -> Message;
        f_convert_df_sci_names_format_6_to_GNR: Input -> Output -> Message;
        f_phylotastic_GetPhylogeneticTree_Phylomatic_GET: Input -> Output -> Output -> Message;
        f_names_extraction_tree: Input -> Output -> Message;
        f_names_extraction_text: Input -> Output -> Message;
        f_phylotastic_ResolvedScientificNames_OT_TNRS_POST: Input -> Output -> Output -> Message;
        f_convert_df_sci_names_format_2_to_4: Input -> Output -> Message;
        tree_figure: Format -> Format -> Message;
        d_i_phylotastic_FindScientificNamesFromWeb_GNRD_GET: Input -> Format -> Message;
        d_i_phylotastic_FindScientificNamesFromFreeText_GNRD_GET: Input -> Format -> Message;
        d_i_phylotastic_ResolvedScientificNames_GNR_TNRS_GET: Input -> Format -> Message;
        d_i_phylotastic_ResolvedScientificNames_GNR_TNRS_POST: Input -> Format -> Message;
        d_i_phylotastic_ResolvedScientificNames_OT_TNRS_GET: Input -> Format -> Message;
        d_i_phylotastic_ResolvedScientificNames_OT_TNRS_POST: Input -> Format -> Message;
        d_i_phylotastic_GetAllSpeciesFromTaxon_OT_GET: Input -> Format -> Message;
        d_i_phylotastic_GetPhylogeneticTree_OT_GET: Input -> Format -> Message;
        d_i_phylotastic_GetPhylogeneticTree_OT_POST: Input -> Format -> Message;
        d_i_phylotastic_GetPhylogeneticTree_PhyloT_GET: Input -> Format -> Message;
        d_i_phylotastic_GetPhylogeneticTree_PhyloT_POST: Input -> Format -> Message;
        d_i_phylotastic_GetPhylogeneticTree_Phylomatic_GET: Input -> Format -> Message;
        d_i_phylotastic_GetPhylogeneticTree_Phylomatic_POST: Input -> Format -> Message;
        d_i_phylotastic_GetAllSpeciesFromTaxon_Country_OT_GET: Input -> Format -> Message;
        d_i_phylotastic_GetSpeciesOfTaxon_Genome_NCBI_GET: Input -> Format -> Message;
        d_i_google_ConvertCountryCodeToName_GET: Input -> Format -> Message;
        d_i_openTree_GetTaxonomyNameFromSciName_GET: Input -> Format -> Message;
        d_i_phylotastic_GetSpeciesScientificNameFromCommonName_NCBI_GET: Input -> Format -> Message;
        d_i_phylotastic_CompareTrees_Sym_Dendropy_POST: Input -> Format -> Message;
        d_i_phylotastic_CompareTrees_BL_Dendropy_POST: Input -> Format -> Message;
        d_i_phylotastic_GetChronograms_ScaledSpeciesTree_DateLife_POST: Input -> Format -> Message;
        d_i_phylotastic_GetMetadata_Chronogram_DateLife_POST: Input -> Format -> Message;
        d_i_phylotastic_FindScientificNamesFromWeb_CS_NMSU_GET: Input -> Format -> Message;
        d_i_phylotastic_ExtractSpeciesNames_From_Gene_Tree_GET: Input -> Format -> Message;
        d_i_phylotastic_GetReconciliationTree_GET: Input -> Format -> Message;
        d_i_phylotastic_GenerateGeneTree_From_Genes: Input -> Format -> Message;
        d_i_phylotastic_GeneTree_Scaling: Input -> Format -> Message;
        d_i_convert_df_text_format_raw_to_plain: Input -> Format -> Message;
        d_i_convert_df_sci_names_format_1_to_3: Input -> Format -> Message;
        d_i_convert_df_sci_names_format_3_to_5: Input -> Format -> Message;
        d_i_convert_df_sci_names_format_5_to_GNR: Input -> Format -> Message;
        d_i_convert_df_sci_names_format_5_to_OT: Input -> Format -> Message;
        d_i_convert_df_sci_names_format_2_to_4: Input -> Format -> Message;
        d_i_convert_df_sci_names_format_4_to_6: Input -> Format -> Message;
        d_i_convert_df_sci_names_format_6_to_GNR: Input -> Format -> Message;
        d_i_convert_df_sci_names_format_6_to_OT: Input -> Format -> Message;
        d_i_convert_df_resolved_names_format_GNR_to_OT: Input -> Format -> Message;
        d_i_convert_df_resolved_names_format_GNR_to_Phylomatic: Input -> Format -> Message;
        d_i_convert_df_resolved_names_format_GNR_to_PhyloT: Input -> Format -> Message;
        d_i_convert_df_resolved_names_format_1_to_3: Input -> Format -> Message;
        d_i_convert_df_resolved_names_format_3_to_5: Input -> Format -> Message;
        d_i_convert_df_resolved_names_format_5_to_OT: Input -> Format -> Message;
        d_i_convert_df_resolved_names_format_5_to_PhyloT: Input -> Format -> Message;
        d_i_convert_df_resolved_names_format_5_to_Phylomatic: Input -> Format -> Message;
        d_i_convert_df_resolved_names_format_2_to_4: Input -> Format -> Message;
        d_i_convert_df_resolved_names_format_4_to_6: Input -> Format -> Message;
        d_i_convert_df_resolved_names_format_6_to_ALL_COMBO: Input -> Format -> Message;
        d_i_convert_df_taxons_format_GNR_to_OT: Input -> Format -> Message;
        d_i_convert_df_taxons_format_GNR_to_Phylomatic: Input -> Format -> Message;
        d_i_convert_df_taxons_format_GNR_to_PhyloT: Input -> Format -> Message;
        d_i_convert_df_taxons_format_1_to_3: Input -> Format -> Message;
        d_i_convert_df_taxons_format_3_to_5: Input -> Format -> Message;
        d_i_convert_df_taxons_format_5_to_OT: Input -> Format -> Message;
        d_i_convert_df_taxons_format_5_to_PhyloT: Input -> Format -> Message;
        d_i_convert_df_taxons_format_5_to_Phylomatic: Input -> Format -> Message;
        d_i_convert_df_taxons_format_2_to_4: Input -> Format -> Message;
        d_i_convert_df_taxons_format_4_to_6: Input -> Format -> Message;
        d_i_convert_df_taxons_format_6_to_ALL_COMBO: Input -> Format -> Message;
        d_i_convert_species_tree_format_NewickTree_to_ALL_COMBO: Input -> Format -> Message;
        d_i_convert_gene_tree_format_NewickTree_to_ALL_COMBO: Input -> Format -> Message;
        d_i_convert_species_tree_format_PhyloTree_to_NMSU: Input -> Format -> Message;
        d_i_convert_gene_tree_format_PhyloTree_to_NMSU: Input -> Format -> Message;
        d_i_convert_species_tree_format_NMSU_to_NewickTree: Input -> Format -> Message;
        d_i_convert_gene_tree_format_NMSU_to_NewickTree: Input -> Format -> Message;
        d_i_convert_species_tree_format_PhyloTree_to_phylo4Tree: Input -> Format -> Message;
        d_i_convert_gene_tree_format_PhyloTree_to_phylo4Tree: Input -> Format -> Message;
        d_i_convert_species_tree_format_Phylo4Tree_to_PhyloTree: Input -> Format -> Message;
        d_i_convert_gene_tree_format_Phylo4Tree_to_PhyloTree: Input -> Format -> Message;
        d_i_convert_species_tree_format_1_to_2: Input -> Format -> Message;
        d_i_convert_gene_tree_format_1_to_2: Input -> Format -> Message;
        d_i_convert_species_tree_format_2_to_pHYLIPTree: Input -> Format -> Message;
        d_i_convert_gene_tree_format_2_to_pHYLIPTree: Input -> Format -> Message;
        d_i_convert_species_tree_format_pHYLIPTree_to_PhyloTree: Input -> Format -> Message;
        d_i_convert_gene_tree_format_pHYLIPTree_to_PhyloTree: Input -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromWeb_GNRD_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromWeb_GNRD_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromWeb_GNRD_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromFreeText_GNRD_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromFreeText_GNRD_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromFreeText_GNRD_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_GNR_TNRS_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_GNR_TNRS_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_GNR_TNRS_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_GNR_TNRS_POST: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_GNR_TNRS_POST: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_GNR_TNRS_POST: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_OT_TNRS_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_OT_TNRS_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_OT_TNRS_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_OT_TNRS_POST: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_OT_TNRS_POST: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_OT_TNRS_POST: Output -> Format -> Message;
        d_o_phylotastic_GetAllSpeciesFromTaxon_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_GetAllSpeciesFromTaxon_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_GetAllSpeciesFromTaxon_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_OT_POST: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_OT_POST: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_PhyloT_GET: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_PhyloT_GET: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_PhyloT_POST: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_PhyloT_POST: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_Phylomatic_GET: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_Phylomatic_GET: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_Phylomatic_POST: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_Phylomatic_POST: Output -> Format -> Message;
        d_o_phylotastic_GetAllSpeciesFromTaxon_Country_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_GetAllSpeciesFromTaxon_Country_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_GetAllSpeciesFromTaxon_Country_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_GetSpeciesOfTaxon_Genome_NCBI_GET: Output -> Format -> Message;
        d_o_phylotastic_GetSpeciesOfTaxon_Genome_NCBI_GET: Output -> Format -> Message;
        d_o_phylotastic_GetSpeciesOfTaxon_Genome_NCBI_GET: Output -> Format -> Message;
        d_o_google_ConvertCountryCodeToName_GET: Output -> Format -> Message;
        d_o_openTree_GetTaxonomyNameFromSciName_GET: Output -> Format -> Message;
        d_o_phylotastic_GetSpeciesScientificNameFromCommonName_NCBI_GET: Output -> Format -> Message;
        d_o_phylotastic_GetSpeciesScientificNameFromCommonName_NCBI_GET: Output -> Format -> Message;
        d_o_phylotastic_GetSpeciesScientificNameFromCommonName_NCBI_GET: Output -> Format -> Message;
        d_o_phylotastic_CompareTrees_Sym_Dendropy_POST: Output -> Format -> Message;
        d_o_phylotastic_CompareTrees_Sym_Dendropy_POST: Output -> Format -> Message;
        d_o_phylotastic_CompareTrees_Sym_Dendropy_POST: Output -> Format -> Message;
        d_o_phylotastic_CompareTrees_BL_Dendropy_POST: Output -> Format -> Message;
        d_o_phylotastic_CompareTrees_BL_Dendropy_POST: Output -> Format -> Message;
        d_o_phylotastic_CompareTrees_BL_Dendropy_POST: Output -> Format -> Message;
        d_o_phylotastic_GetChronograms_ScaledSpeciesTree_DateLife_POST: Output -> Format -> Message;
        d_o_phylotastic_GetMetadata_Chronogram_DateLife_POST: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromWeb_CS_NMSU_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromWeb_CS_NMSU_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromWeb_CS_NMSU_GET: Output -> Format -> Message;
        d_o_phylotastic_ExtractSpeciesNames_From_Gene_Tree_GET: Output -> Format -> Message;
        d_o_phylotastic_ExtractSpeciesNames_From_Gene_Tree_GET: Output -> Format -> Message;
        d_o_phylotastic_ExtractSpeciesNames_From_Gene_Tree_GET: Output -> Format -> Message;
        d_o_phylotastic_GetReconciliationTree_GET: Output -> Format -> Message;
        d_o_phylotastic_GenerateGeneTree_From_Genes: Output -> Format -> Message;
        d_o_phylotastic_GeneTree_Scaling: Output -> Format -> Message;
        d_o_convert_df_text_format_raw_to_plain: Output -> Format -> Message;
        d_o_convert_df_sci_names_format_1_to_3: Output -> Format -> Message;
        d_o_convert_df_sci_names_format_3_to_5: Output -> Format -> Message;
        d_o_convert_df_sci_names_format_5_to_GNR: Output -> Format -> Message;
        d_o_convert_df_sci_names_format_5_to_OT: Output -> Format -> Message;
        d_o_convert_df_sci_names_format_2_to_4: Output -> Format -> Message;
        d_o_convert_df_sci_names_format_4_to_6: Output -> Format -> Message;
        d_o_convert_df_sci_names_format_6_to_GNR: Output -> Format -> Message;
        d_o_convert_df_sci_names_format_6_to_OT: Output -> Format -> Message;
        d_o_convert_df_resolved_names_format_GNR_to_OT: Output -> Format -> Message;
        d_o_convert_df_resolved_names_format_GNR_to_Phylomatic: Output -> Format -> Message;
        d_o_convert_df_resolved_names_format_GNR_to_PhyloT: Output -> Format -> Message;
        d_o_convert_df_resolved_names_format_1_to_3: Output -> Format -> Message;
        d_o_convert_df_resolved_names_format_3_to_5: Output -> Format -> Message;
        d_o_convert_df_resolved_names_format_5_to_OT: Output -> Format -> Message;
        d_o_convert_df_resolved_names_format_5_to_PhyloT: Output -> Format -> Message;
        d_o_convert_df_resolved_names_format_5_to_Phylomatic: Output -> Format -> Message;
        d_o_convert_df_resolved_names_format_2_to_4: Output -> Format -> Message;
        d_o_convert_df_resolved_names_format_4_to_6: Output -> Format -> Message;
        d_o_convert_df_resolved_names_format_6_to_ALL_COMBO: Output -> Format -> Message;
        d_o_convert_df_resolved_names_format_6_to_ALL_COMBO: Output -> Format -> Message;
        d_o_convert_df_resolved_names_format_6_to_ALL_COMBO: Output -> Format -> Message;
        d_o_convert_df_taxons_format_GNR_to_OT: Output -> Format -> Message;
        d_o_convert_df_taxons_format_GNR_to_Phylomatic: Output -> Format -> Message;
        d_o_convert_df_taxons_format_GNR_to_PhyloT: Output -> Format -> Message;
        d_o_convert_df_taxons_format_1_to_3: Output -> Format -> Message;
        d_o_convert_df_taxons_format_3_to_5: Output -> Format -> Message;
        d_o_convert_df_taxons_format_5_to_OT: Output -> Format -> Message;
        d_o_convert_df_taxons_format_5_to_PhyloT: Output -> Format -> Message;
        d_o_convert_df_taxons_format_5_to_Phylomatic: Output -> Format -> Message;
        d_o_convert_df_taxons_format_2_to_4: Output -> Format -> Message;
        d_o_convert_df_taxons_format_4_to_6: Output -> Format -> Message;
        d_o_convert_df_taxons_format_6_to_ALL_COMBO: Output -> Format -> Message;
        d_o_convert_df_taxons_format_6_to_ALL_COMBO: Output -> Format -> Message;
        d_o_convert_df_taxons_format_6_to_ALL_COMBO: Output -> Format -> Message;
        d_o_convert_species_tree_format_NewickTree_to_ALL_COMBO: Output -> Format -> Message;
        d_o_convert_species_tree_format_NewickTree_to_ALL_COMBO: Output -> Format -> Message;
        d_o_convert_species_tree_format_NewickTree_to_ALL_COMBO: Output -> Format -> Message;
        d_o_convert_gene_tree_format_NewickTree_to_ALL_COMBO: Output -> Format -> Message;
        d_o_convert_gene_tree_format_NewickTree_to_ALL_COMBO: Output -> Format -> Message;
        d_o_convert_gene_tree_format_NewickTree_to_ALL_COMBO: Output -> Format -> Message;
        d_o_convert_species_tree_format_PhyloTree_to_NMSU: Output -> Format -> Message;
        d_o_convert_gene_tree_format_PhyloTree_to_NMSU: Output -> Format -> Message;
        d_o_convert_species_tree_format_NMSU_to_NewickTree: Output -> Format -> Message;
        d_o_convert_gene_tree_format_NMSU_to_NewickTree: Output -> Format -> Message;
        d_o_convert_species_tree_format_PhyloTree_to_phylo4Tree: Output -> Format -> Message;
        d_o_convert_gene_tree_format_PhyloTree_to_phylo4Tree: Output -> Format -> Message;
        d_o_convert_species_tree_format_Phylo4Tree_to_PhyloTree: Output -> Format -> Message;
        d_o_convert_gene_tree_format_Phylo4Tree_to_PhyloTree: Output -> Format -> Message;
        d_o_convert_species_tree_format_1_to_2: Output -> Format -> Message;
        d_o_convert_gene_tree_format_1_to_2: Output -> Format -> Message;
        d_o_convert_species_tree_format_2_to_pHYLIPTree: Output -> Format -> Message;
        d_o_convert_gene_tree_format_2_to_pHYLIPTree: Output -> Format -> Message;
        d_o_convert_species_tree_format_pHYLIPTree_to_PhyloTree: Output -> Format -> Message;
        d_o_convert_gene_tree_format_pHYLIPTree_to_PhyloTree: Output -> Format -> Message;
        i_resource_SetOfTaxon: Input;
        i_resource_ScientificName: Input;
        i_resource_speciesTree: Input;
        i_resource_geneTree: Input;
        i_resource_CountryName: Input;
        i_resource_SetOfGeneStrings: Input;
        i_resource_FreeText: Input;
        i_resource_CommonName: Input;
        i_resource_taxon: Input;
        i_phylomatic_method: Input;
        i_resource_SetOfResolvedName: Input;
        i_resource_WebURL: Input;
        i_resource_CountryCode: Input;
        i_resource_Document: Input;
        i_resource_SetOfSciName: Input;
        i_resource_Tree: Input;
        i_phylotastic_resources: Input;
        i_resource_speciesTree: Input;
        i_resource_geneTree: Input;
        i_resource_CountryName: Input;
        i_resource_SetOfGeneStrings: Input;
        i_resource_String: Input;
        i_phylotastic_concept: Input;
        i_phylomatic_method: Input;
        i_resource_Tree: Input;
        i_resource_URI: Input;
        i_resource_SetOfTaxon: Input;
        i_resource_Name: Input;
        i_network: Input;
        i_resource_SetOfResolvedName: Input;
        i_resource_FreeText: Input;
        i_resource_Text: Input;
        i_resource_SetOfScientificNames: Input;
        i_resource_WebURL: Input;
        i_resource_SetOfThings: Input;
        i_resource_SpeciesName: Input;
        i_resource_ScientificName: Input;
        i_resource_CommonName: Input;
        i_resource_method: Input;
        i_resource_Number: Input;
        i_resource_CountryCode: Input;
        i_resource_Document: Input;
        i_speciesTree: Input;
        i_resource_Object: Input;
        i_resource_SetOfStrings: Input;
        i_resource_taxon: Input;
        i_tree: Input;
        i_resource_SetOfSciName: Input;
        i_resource_SetOfNames: Input;
        o_resource_SetOfTaxon: Output;
        o_resource_ScientificName: Output;
        o_resource_speciesTree: Output;
        o_resource_geneTree: Output;
        o_resource_CountryName: Output;
        o_resource_SetOfResolvedName: Output;
        o_resource_FreeText: Output;
        o_resource_taxon: Output;
        o_resource_Image: Output;
        o_resource_SetOfNames: Output;
        o_resource_speciesTree_with_BranchLengths: Output;
        o_resource_reconcileTree: Output;
        o_resource_metadata_tree_scaling: Output;
        o_resource_WebURL: Output;
        o_ws_response_message: Output;
        o_resource_SetOfSciName: Output;
        o_resource_Tree: Output;
        o_resource_AreSameTree: Output;
        o_phylotastic_resources: Output;
        o_resource_speciesTree: Output;
        o_resource_geneTree: Output;
        o_resource_CountryName: Output;
        o_resource_String: Output;
        o_resource_reconcileTree: Output;
        o_message: Output;
        o_phylotastic_concept: Output;
        o_resource_Tree: Output;
        o_resource_metadata_tree_scaling: Output;
        o_resource_SetOfTaxon: Output;
        o_resource_Name: Output;
        o_network: Output;
        o_resource_SetOfResolvedName: Output;
        o_resource_FreeText: Output;
        o_resource_Text: Output;
        o_resource_SetOfScientificNames: Output;
        o_resource_WebURL: Output;
        o_resource_URI: Output;
        o_resource_SetOfThings: Output;
        o_resource_SpeciesName: Output;
        o_resource_AreSameTree: Output;
        o_resource_ScientificName: Output;
        o_reconcileTree: Output;
        o_resource_Image: Output;
        o_resource_speciesTree_with_BranchLengths: Output;
        o_resource_Boolean: Output;
        o_speciesTree: Output;
        o_resource_Object: Output;
        o_ws_response_message: Output;
        o_resource_SetOfStrings: Output;
        o_resource_taxon: Output;
        o_tree: Output;
        o_resource_SetOfSciName: Output;
        o_resource_SetOfNames: Output;
        d_http_url: Format;
        d_plain_text: Format;
        d_raw_names_format_GNR: Format;
        d_raw_names_format_OT: Format;
        d_string: Format;
        d_resolved_names_format_OT: Format;
        d_resolved_names_format_PhyloT: Format;
        d_resolved_names_format_Phylomatic: Format;
        d_integer: Format;
        d_newickTree: Format;
        d_compare_tree_format: Format;
        d_data_format_E: Format;
        d_list_of_strings: Format;
        d_raw_text: Format;
        d_raw_names_format_1: Format;
        d_raw_names_format_3: Format;
        d_raw_names_format_5: Format;
        d_raw_names_format_2: Format;
        d_raw_names_format_4: Format;
        d_raw_names_format_6: Format;
        d_resolved_names_format_GNR: Format;
        d_resolved_names_format_1: Format;
        d_resolved_names_format_3: Format;
        d_resolved_names_format_5: Format;
        d_resolved_names_format_2: Format;
        d_resolved_names_format_4: Format;
        d_resolved_names_format_6: Format;
        d_phyloTree: Format;
        d_nmsu_tree_format: Format;
        d_phylo4Tree: Format;
        d_tree_format_1: Format;
        d_tree_format_2: Format;
        d_pHYLIPTree: Format;
        d_boolean: Format;
        d_figure: Format;
        d_tree: Format;
}