abstract Phylo = {
    flags startcat = DMessage;
    flags startcat = Message;
    cat
        Message;
        Input;
        Output;
        Format;
    fun
        f_names_extraction_web: Input -> Output -> Message;
        f_tree_retrieval_operation: Output -> Message;
        f_names_extraction_document: Input -> Output -> Message;
        f_names_extraction_text: Input -> Output -> Message;
        f_taxon_to_species_by_genome: Input -> Output -> Output -> Message;
        f_gene_based_extraction: Input -> Output -> Output -> Message;
        f_phylotastic_ResolvedScientificNames_GNR_TNRS_POST: Input -> Output -> Output -> Output -> Message;
        f_taxon_to_species_by_country: Input -> Input -> Output -> Output -> Message;
        f_phylotastic_ResolvedScientificNames_OT_TNRS_POST: Input -> Output -> Output -> Output -> Message;
        f_phylotastic_ResolvedScientificNames_OT_TNRS_GET: Input -> Output -> Output -> Output -> Message;
        f_phylotastic_GetPhylogeneticTree_OT_GET: Input -> Output -> Output -> Message;
        f_phylotastic_GetAllSpeciesFromTaxon_OT_GET: Input -> Output -> Output -> Message;
        f_branch_length_comparison_operation: Input -> Message;
        f_phylotastic_GetPhylogeneticTree_OT_POST: Input -> Output -> Output -> Message;
        f_tree_scaling_operation: Input -> Output -> Message;
        f_symmetric_comparison_operation: Input -> Message;
        f_phylotastic_FindScientificNamesFromWeb_GNRD_GET: Input -> Output -> Output -> Message;
        f_gene_tree_scaling: Input -> Output -> Message;
        f_phylotastic_GetSpeciesOfTaxon_Genome_NCBI_GET: Input -> Output -> Output -> Message;
        f_phylotastic_FindScientificNamesFromFreeText_GNRD_GET: Input -> Output -> Output -> Message;
        f_google_ConvertCountryCodeToName_GET: Input -> Output -> Message;
        f_taxonomy_based_extraction: Input -> Output -> Message;
        f_openTree_GetScientificNameFromAName_GET: Input -> Output -> Message;
        f_openTree_GetTaxonomyNameFromSciName_GET: Input -> Output -> Message;
        f_common_name_to_scientific_name: Input -> Output -> Message;
        f_phylotastic_FindScientificNamesFromWeb_CS_NMSU_GET: Input -> Output -> Output -> Message;
        f_phylotastic_GenerateGeneTree_From_Genes: Input -> Output -> Message;
        f_phylotastic_GetReconciliationTree_GET: Input -> Input -> Output -> Message;
        f_phylotastic_GeneTree_Scaling: Input -> Output -> Message;
        f_phylogeny_based_extraction: Input -> Output -> Message;
        f_scientific_name_to_taxonomy: Input -> Output -> Message;
        f_tree_extraction_operation: Output -> Message;
        f_names_operation: Output -> Message;
        f_names_extraction_tree: Input -> Output -> Message;
        f_phylotastic_ExtractSpeicesName_From_Gene_Tree_GET: Input -> Output -> Output -> Message;
        f_taxon_to_species_operation: Input -> Output -> Output -> Message;
        f_names_resolution_operation: Input -> Output -> Message;
        f_phylotastic_GetAllSpeciesFromTaxon_Country_OT_GET: Input -> Input -> Output -> Output -> Message;
        f_names_extraction_operation: Output -> Message;
        f_tree_generation: Output -> Message;
        f_country_code_to_name: Input -> Output -> Message;
        f_tree_comparison: Input -> Message;
        f_phylotastic_ResolvedScientificNames_GNR_TNRS_GET: Input -> Output -> Output -> Output -> Message;
        f_tree_transformation: Input -> Output -> Message;
        f_tree_visualization: Input -> Output -> Message;
        f_tree_reconciliation: Input -> Input -> Output -> Message;
        f_look_up_scientific_name: Output -> Message;
        f_look_up_taxonomy: Output -> Message;
        tree_figure: Format -> Format -> Message;
        d_i_phylotastic_GeneTree_Scaling: Input -> Format -> Message;
        d_i_phylotastic_GetReconciliationTree_GET: Input -> Format -> Message;
        d_i_phylotastic_GenerateGeneTree_From_Genes: Input -> Format -> Message;
        d_i_phylotastic_ExtractSpeicesName_From_Gene_Tree_GET: Input -> Format -> Message;
        d_i_google_ConvertCountryCodeToName_GET: Input -> Format -> Message;
        d_i_phylotastic_GetSpeciesOfTaxon_Genome_NCBI_GET: Input -> Format -> Message;
        d_i_phylotastic_ResolvedScientificNames_OT_TNRS_GET: Input -> Format -> Message;
        d_i_phylotastic_GetAllSpeciesFromTaxon_Country_OT_GET: Input -> Format -> Message;
        d_i_openTree_GetScientificNameFromAName_GET: Input -> Format -> Message;
        d_i_phylotastic_GetAllSpeciesFromTaxon_OT_GET: Input -> Format -> Message;
        d_i_phylotastic_GetPhylogeneticTree_OT_GET: Input -> Format -> Message;
        d_i_phylotastic_GetPhylogeneticTree_OT_POST: Input -> Format -> Message;
        d_i_phylotastic_FindScientificNamesFromWeb_GNRD_GET: Input -> Format -> Message;
        d_i_phylotastic_FindScientificNamesFromWeb_CS_NMSU_GET: Input -> Format -> Message;
        d_i_phylotastic_ResolvedScientificNames_GNR_TNRS_GET: Input -> Format -> Message;
        d_i_phylotastic_ResolvedScientificNames_GNR_TNRS_POST: Input -> Format -> Message;
        d_i_openTree_GetTaxonomyNameFromSciName_GET: Input -> Format -> Message;
        d_i_phylotastic_ResolvedScientificNames_OT_TNRS_POST: Input -> Format -> Message;
        d_i_phylotastic_FindScientificNamesFromFreeText_GNRD_GET: Input -> Format -> Message;
        d_o_phylotastic_GenerateGeneTree_From_Genes: Output -> Format -> Message;
        d_o_phylotastic_ExtractSpeicesName_From_Gene_Tree_GET: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_OT_POST: Output -> Format -> Message;
        d_o_phylotastic_ExtractSpeicesName_From_Gene_Tree_GET: Output -> Format -> Message;
        d_o_phylotastic_ExtractSpeicesName_From_Gene_Tree_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromWeb_CS_NMSU_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromWeb_CS_NMSU_GET: Output -> Format -> Message;
        d_o_openTree_GetScientificNameFromAName_GET: Output -> Format -> Message;
        d_o_openTree_GetTaxonomyNameFromSciName_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromWeb_GNRD_GET: Output -> Format -> Message;
        d_o_google_ConvertCountryCodeToName_GET: Output -> Format -> Message;
        d_o_phylotastic_GeneTree_Scaling: Output -> Format -> Message;
        d_o_phylotastic_GetSpeciesOfTaxon_Genome_NCBI_GET: Output -> Format -> Message;
        d_o_phylotastic_GetSpeciesOfTaxon_Genome_NCBI_GET: Output -> Format -> Message;
        d_o_phylotastic_GetSpeciesOfTaxon_Genome_NCBI_GET: Output -> Format -> Message;
        d_o_phylotastic_GetReconciliationTree_GET: Output -> Format -> Message;
        d_o_phylotastic_GetAllSpeciesFromTaxon_Country_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_GetAllSpeciesFromTaxon_Country_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_ExtractSpeicesName_From_Gene_Tree_GET: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_OT_POST: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_GetPhylogeneticTree_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_GetAllSpeciesFromTaxon_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_GetAllSpeciesFromTaxon_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_OT_TNRS_POST: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_OT_TNRS_POST: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_OT_TNRS_POST: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromWeb_CS_NMSU_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromWeb_GNRD_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_OT_TNRS_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_OT_TNRS_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_GNR_TNRS_POST: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_OT_TNRS_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_OT_TNRS_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_GNR_TNRS_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_GNR_TNRS_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_OT_TNRS_POST: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_GNR_TNRS_POST: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_GNR_TNRS_POST: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromFreeText_GNRD_GET: Output -> Format -> Message;
        d_o_phylotastic_GetAllSpeciesFromTaxon_Country_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_GNR_TNRS_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromWeb_CS_NMSU_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_GNR_TNRS_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromFreeText_GNRD_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromWeb_GNRD_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromFreeText_GNRD_GET: Output -> Format -> Message;
        d_o_phylotastic_ResolvedScientificNames_GNR_TNRS_POST: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromFreeText_GNRD_GET: Output -> Format -> Message;
        d_o_phylotastic_GetAllSpeciesFromTaxon_OT_GET: Output -> Format -> Message;
        d_o_phylotastic_FindScientificNamesFromWeb_GNRD_GET: Output -> Format -> Message;
        i_resource_SetOfTaxon: Input;
        i_resource_CountryName: Input;
        i_resource_Name: Input;
        i_resource_geneTree: Input;
        i_resource_SetOfPhylogenyTrees: Input;
        i_resource_SetOfGeneStrings: Input;
        i_resource_FreeText: Input;
        i_resource_taxon: Input;
        i_resource_ScientificName: Input;
        i_resource_SetOfResolvedName: Input;
        i_resource_speciesTree: Input;
        i_resource_WebURL: Input;
        i_resource_CountryCode: Input;
        i_resource_Document: Input;
        i_resource_SetOfSciName: Input;
        i_resource_Tree: Input;
        i_phylotastic_resources: Input;
        i_resource_speciesTree: Input;
        i_resource_geneTree: Input;
        i_resource_CountryName: Input;
        i_resource_SetOfGeneStrings: Input;
        i_resource_String: Input;
        i_phylotastic_concept: Input;
        i_resource_Tree: Input;
        i_resource_URI: Input;
        i_resource_SetOfTaxon: Input;
        i_resource_Name: Input;
        i_network: Input;
        i_resource_SetOfNames: Input;
        i_resource_FreeText: Input;
        i_resource_Text: Input;
        i_resource_SetOfScientificNames: Input;
        i_resource_WebURL: Input;
        i_resource_SetOfThings: Input;
        i_resource_ScientificName: Input;
        i_resource_Number: Input;
        i_resource_SetOfObjects: Input;
        i_resource_CountryCode: Input;
        i_resource_Document: Input;
        i_speciesTree: Input;
        i_resource_Object: Input;
        i_resource_SetOfStrings: Input;
        i_resource_taxon: Input;
        i_tree: Input;
        i_resource_SetOfSciName: Input;
        i_resource_SetOfResolvedName: Input;
        o_resource_SetOfTaxon: Output;
        o_resource_ScientificName: Output;
        o_resource_speciesTree: Output;
        o_resource_geneTree: Output;
        o_resource_CountryName: Output;
        o_resource_SetOfResolvedName: Output;
        o_resource_taxon: Output;
        o_resource_Image: Output;
        o_resource_SetOfNames: Output;
        o_resource_reconcileTree: Output;
        o_resource_SetOfSciName: Output;
        o_resource_Tree: Output;
        o_phylotastic_resources: Output;
        o_resource_speciesTree: Output;
        o_resource_geneTree: Output;
        o_resource_CountryName: Output;
        o_resource_String: Output;
        o_resource_reconcileTree: Output;
        o_phylotastic_concept: Output;
        o_resource_Tree: Output;
        o_resource_SetOfTaxon: Output;
        o_resource_Name: Output;
        o_network: Output;
        o_resource_SetOfResolvedName: Output;
        o_resource_Text: Output;
        o_resource_SetOfScientificNames: Output;
        o_resource_SetOfThings: Output;
        o_resource_ScientificName: Output;
        o_reconcileTree: Output;
        o_resource_Image: Output;
        o_speciesTree: Output;
        o_resource_Object: Output;
        o_resource_SetOfStrings: Output;
        o_resource_taxon: Output;
        o_tree: Output;
        o_resource_SetOfSciName: Output;
        o_resource_SetOfNames: Output;
        d_newickTree: Format;
        d_list_of_strings: Format;
        d_integer: Format;
        d_string: Format;
        d_names_format_resolved_OT: Format;
        d_data_format_D: Format;
        d_data_format_E: Format;
        d_names_format_resolved_GNR: Format;
        d_plain_text: Format;
        d_nmsu_tree_format: Format;
        d_names_format_2: Format;
        d_names_format_1: Format;
        d_figure: Format;
        d_tree: Format;
}